### ISSUE TITLE
Web Interface?

### ISSUE THREAD

**Issue by awkwords** [nerdynick/MemcachedManager#1]
Does this application have a web interface ?

**Comment by nerdynick** [comment]
It doesn't. The original goal was just a standalone app. However there
is this Stackoverflow for a PHP based one that is included in the PHP
client install http://stackoverflow.com/questions/5127556/php-memcached-stats-page.

If you can provided details of what your wanting I can look into the
possibility of creating server based install with web interface.

On Tue, Nov 29, 2011 at 4:09 PM, i0nic
reply@reply.github.com
wrote:

> Does this application have a web interface ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nerdynick/MemcachedManager/issues/1

## 

## Nick Verbeck - NerdyNick

NerdyNick.com
Coloco.ubuntu-rocks.org
